name: Deploy to Github Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Build
        env:
          # `base64 .env.production | pbcopy` and paste into github environment secrets for this repo
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          NEXT_PUBLIC_PIPEDREAM_API_URL: https://eofdotsr4ewj68m.m.pipedream.net
          NEXT_PUBLIC_PIPEDREAM_INVOICE_URL: https://eovuxgd9pdeohx.m.pipedream.net
        run: |
          # Extract the environment variables from the base64 encoded string into the .env.local for build
          echo $ENVIRONMENT | base64 -d > .env.local
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn run build
          yarn run export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
